project:
  type: website

website:
  margin-header: |
    ![](/logo_bekigeki.png)
  search:
    location: navbar
    type: overlay
  title: "BeKiGeKi"
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: Ergebnisse
        contents:
          - href: 001.qmd
            text: Teilnehmerzahlen
          - href: 002.qmd
            text: Versuch einer Klassifikation
      - section: Sport-Veranstaltungen 
        contents:
          - href: 003.qmd
            text: 2018-2023
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



